name = "Nim"
code_fence_block_name = "nim"
grammar = "nim"
path_suffixes = ["nim", "nims", "nimble", "nim.cfg"]


autoclose_before = ";:.,=}])>"

brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "<", end = ">", close = false, newline = true, not_in = ["comment", "string"] },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment", "string"] },
    { start = "'", end = "'", close = true, newline = false, not_in = ["comment", "string"] },
    { start = "`", end = "`", close = true, newline = true, not_in = ["comment", "string"] },
    { start = "/*", end = "*/", close = true, newline = true, not_in = ["comment", "string"] },
]
tab_size = 2
increase_indent_pattern = ":\\s*$|=\\s*$|^\\s*(if|else|elif|case|of|while|for|block|proc|func|method|iterator|macro|template|type|when)\\b"
decrease_indent_pattern = "^\\s*(else|elif|of|except|finally)\\b"

[overrides.element]
line_comments = ["#"]
block_comment = ["#[ ", " ]#"]
comment_continuation = { insert = "# " }
