on:
  push:
    tags:
      - "v*"

jobs:
  homebrew:
    name: bump-zed-extension
    runs-on: ubuntu-latest
    steps:
      - uses: huacnlee/zed-extension-action@v1.0.0
        with:
          extension-name: nim
          push-to: foxoman/extensions
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
